default:
  golem_name: IsoRankershiny
  golem_version: 0.0.0.9000
  app_prod: no
  dependencies:
    - bsicons
    - config
    - DT
    - golem
    - htmltools
    - magrittr
    - plotly
    - shiny
    - shinydashboard
    - shinyFiles
    - shinyhelper
    - shinyjs
    - skimr
    - tools
    - utils

production:
  app_prod: yes

dev:
  golem_wd: !expr golem::pkg_path()

